# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - devolop

jobs:
  - job: Build
    displayName: "Build and Push"
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'Docker Hub'
          repository: 'performs/performs-fe-stg'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: 'latest'

      - task: Kubernetes@1
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceEndpoint: 'Digitalocean Kubernetes Stg'
          command: 'rollout'
          arguments: 'restart deploy performs-fe-stg'