import { NavigationConfigTypes } from "~/@main/types/Config-Types";
import authRoles from "../auth/authRoles";

const navigationConfig: NavigationConfigTypes[] = [
  {
    id: "home-page",
    title: "Home",
    translate: "HOME",
    type: "item",
    icon: "HomeIcon:outline",
    url: "home",
    auth: authRoles.Parent,
  },
  {
    id: "home-page-coach",
    title: "Home",
    translate: "HOME",
    type: "item",
    icon: "HomeIcon:outline",
    url: "coach-home",
    auth: authRoles.Coach,
  },
  {
    id: "home-page-supervisor",
    title: "Home",
    translate: "HOME",
    type: "item",
    icon: "HomeIcon:outline",
    url: "supervisor",
    auth: authRoles.Supervisor,
  },
  {
    id: "scoring",
    title: "Scoring",
    translate: "SCORING",
    type: "item",
    icon: "ChartBarIcon:outline",
    url: "scoring",
    auth: authRoles.Supervisor,
  },
  {
    id: "home-page-admin",
    title: "Home",
    translate: "HOME",
    type: "item",
    icon: "HomeIcon:outline",
    url: "admin",
    auth: authRoles.Admin,
  },
  {
    id: "coaches-page",
    title: "Coaches",
    translate: "COACHES",
    type: "item",
    icon: "UserIcon:outline",
    url: "coaches",
    auth: authRoles.Parent,
  },
  {
    id: "chat-page",
    title: "Chat",
    translate: "CHAT",
    type: "item",
    icon: "EnvelopeIcon:outline",
    url: "chat",
    auth: authRoles.All,
  },
  {
    id: "reports-page",
    title: "Reports",
    translate: "REPORTS",
    type: "item",
    icon: "NewspaperIcon:outline",
    url: "reports",
    auth: authRoles.Parent,
  },
  {
    id: "media-page",
    title: "Media",
    translate: "MEDIA",
    type: "item",
    icon: "BookmarkIcon:outline",
    url: "media",
    auth: authRoles.All,
  },
  {
    id: "subscriptions-page",
    title: "Subscriptions",
    translate: "SUBSCRIPTIONS",
    type: "item",
    icon: "BanknotesIcon:outline",
    url: "subscriptions",
    auth: authRoles.Parent,
  },
  {
    id: "players",
    title: "Players",
    translate: "PLAYERS",
    type: "item",
    icon: "UserCircleIcon:outline",
    url: "players",
    auth: authRoles.Coach,
  },
  {
    id: "coaches-requests",
    title: "Requests",
    translate: "REQUESTS",
    type: "item",
    icon: "UserPlusIcon:outline",
    url: "requests",
    auth: [...authRoles.Admin, ...authRoles.Supervisor],
  },

  {
    id: "main-reports",
    title: "Reports",
    translate: "REPORTS",
    type: "item",
    icon: "NewspaperIcon:outline",
    url: "main-reports",
    auth: [...authRoles.Admin, ...authRoles.Supervisor, ...authRoles.Coach],
  },
];

export default navigationConfig;
